/* eslint-disable react/no-unknown-property */
/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 react.glb -T
    Author: pissang (https://sketchfab.com/YiChen)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/github-octocat-c8a4795ce3fe4b21a4c40895cb9cb6a5
*/

import { Float, useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

interface GitHubLogoProps extends GroupProps {}

const GitHubLogo = ({ ...props }: GitHubLogoProps) => {
  const { nodes, materials } = useGLTF("/models/github_octocat.glb") as any;

  return (
    <Float floatIntensity={1}>
      <group position={[-6, 15, 0]} scale={0.26} {...props} dispose={null}>
        {/* Using the Octocat geometry and materials but keeping original positions */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
          position={[0.004, 9.995, 0.636]}
          scale={0.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.material_1}
          position={[0.002, 9.997, 1.487]}
          scale={0.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.material_2}
          position={[-0.002, 9.994, 1.813]}
          scale={0.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.material_3}
          position={[-0.002, 9.988, 1.8]}
          scale={0.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.material_4}
          position={[-0.001, 9.996, 1.81]}
          scale={0.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.material_5}
          position={[0.012, 10.002, 1.755]}
          scale={0.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.material_6}
          position={[0, 9.995, 1.325]}
          scale={0.05}
        />
      </group>
    </Float>
  );
};

// Preload the model for better performance
useGLTF.preload("/models/github_octocat.glb");

export default GitHubLogo;
